// Code generated by MockGen. DO NOT EDIT.
// Source: internal/webhook/client/client.go

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/nurdsoft/nurd-commerce-core/internal/webhook/entities"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// NotifyOrderStatusChange mocks base method.
func (m *MockClient) NotifyOrderStatusChange(ctx context.Context, req *entities.NotifyOrderStatusChangeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyOrderStatusChange", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyOrderStatusChange indicates an expected call of NotifyOrderStatusChange.
func (mr *MockClientMockRecorder) NotifyOrderStatusChange(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOrderStatusChange", reflect.TypeOf((*MockClient)(nil).NotifyOrderStatusChange), ctx, req)
}
