// Code generated by MockGen. DO NOT EDIT.
// Source: shared/vendors/inventory/printful/service/service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/nurdsoft/nurd-commerce-core/shared/vendors/inventory/printful/entities"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetSyncProduct mocks base method.
func (m *MockService) GetSyncProduct(ctx context.Context, productID int) (*entities.GetSyncProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncProduct", ctx, productID)
	ret0, _ := ret[0].(*entities.GetSyncProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncProduct indicates an expected call of GetSyncProduct.
func (mr *MockServiceMockRecorder) GetSyncProduct(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncProduct", reflect.TypeOf((*MockService)(nil).GetSyncProduct), ctx, productID)
}

// GetSyncProducts mocks base method.
func (m *MockService) GetSyncProducts(ctx context.Context, req entities.GetSyncProductsRequest) (*entities.SyncProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncProducts", ctx, req)
	ret0, _ := ret[0].(*entities.SyncProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncProducts indicates an expected call of GetSyncProducts.
func (mr *MockServiceMockRecorder) GetSyncProducts(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncProducts", reflect.TypeOf((*MockService)(nil).GetSyncProducts), ctx, req)
}
