// Code generated by MockGen. DO NOT EDIT.
// Source: shared/vendors/inventory/salesforce/client/client.go

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/nurdsoft/nurd-commerce-core/shared/vendors/inventory/entities"
	entities0 "github.com/nurdsoft/nurd-commerce-core/shared/vendors/inventory/salesforce/entities"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddOrderItems mocks base method.
func (m *MockClient) AddOrderItems(ctx context.Context, items []*entities0.OrderItem) (*entities0.AddOrderItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrderItems", ctx, items)
	ret0, _ := ret[0].(*entities0.AddOrderItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrderItems indicates an expected call of AddOrderItems.
func (mr *MockClientMockRecorder) AddOrderItems(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderItems", reflect.TypeOf((*MockClient)(nil).AddOrderItems), ctx, items)
}

// CreateOrder mocks base method.
func (m *MockClient) CreateOrder(ctx context.Context, req entities.CreateInventoryOrderRequest) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockClientMockRecorder) CreateOrder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockClient)(nil).CreateOrder), ctx, req)
}

// CreatePriceBookEntry mocks base method.
func (m *MockClient) CreatePriceBookEntry(ctx context.Context, req *entities0.CreateSFPriceBookEntryRequest) (*entities0.CreateSFPriceBookEntryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceBookEntry", ctx, req)
	ret0, _ := ret[0].(*entities0.CreateSFPriceBookEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePriceBookEntry indicates an expected call of CreatePriceBookEntry.
func (mr *MockClientMockRecorder) CreatePriceBookEntry(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceBookEntry", reflect.TypeOf((*MockClient)(nil).CreatePriceBookEntry), ctx, req)
}

// CreateProduct mocks base method.
func (m *MockClient) CreateProduct(ctx context.Context, req *entities0.CreateSFProductRequest) (*entities0.CreateSFProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, req)
	ret0, _ := ret[0].(*entities0.CreateSFProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockClientMockRecorder) CreateProduct(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockClient)(nil).CreateProduct), ctx, req)
}

// CreateUserAccount mocks base method.
func (m *MockClient) CreateUserAccount(ctx context.Context, req *entities0.CreateSFUserRequest) (*entities0.CreateSFUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAccount", ctx, req)
	ret0, _ := ret[0].(*entities0.CreateSFUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAccount indicates an expected call of CreateUserAccount.
func (mr *MockClientMockRecorder) CreateUserAccount(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAccount", reflect.TypeOf((*MockClient)(nil).CreateUserAccount), ctx, req)
}

// CreateUserAddress mocks base method.
func (m *MockClient) CreateUserAddress(ctx context.Context, req *entities0.CreateSFAddressRequest) (*entities0.CreateSFAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAddress", ctx, req)
	ret0, _ := ret[0].(*entities0.CreateSFAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAddress indicates an expected call of CreateUserAddress.
func (mr *MockClientMockRecorder) CreateUserAddress(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAddress", reflect.TypeOf((*MockClient)(nil).CreateUserAddress), ctx, req)
}

// DeleteUserAddress mocks base method.
func (m *MockClient) DeleteUserAddress(ctx context.Context, addressId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAddress", ctx, addressId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAddress indicates an expected call of DeleteUserAddress.
func (mr *MockClientMockRecorder) DeleteUserAddress(ctx, addressId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAddress", reflect.TypeOf((*MockClient)(nil).DeleteUserAddress), ctx, addressId)
}

// GetAccountByID mocks base method.
func (m *MockClient) GetAccountByID(ctx context.Context, accountId string) (*entities0.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, accountId)
	ret0, _ := ret[0].(*entities0.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockClientMockRecorder) GetAccountByID(ctx, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockClient)(nil).GetAccountByID), ctx, accountId)
}

// GetOrderItems mocks base method.
func (m *MockClient) GetOrderItems(ctx context.Context, orderId string) (*entities0.GetOrderItemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItems", ctx, orderId)
	ret0, _ := ret[0].(*entities0.GetOrderItemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItems indicates an expected call of GetOrderItems.
func (mr *MockClientMockRecorder) GetOrderItems(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItems", reflect.TypeOf((*MockClient)(nil).GetOrderItems), ctx, orderId)
}

// UpdateOrderStatus mocks base method.
func (m *MockClient) UpdateOrderStatus(ctx context.Context, req entities.UpdateInventoryOrderStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockClientMockRecorder) UpdateOrderStatus(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockClient)(nil).UpdateOrderStatus), ctx, req)
}

// UpdateUserAccount mocks base method.
func (m *MockClient) UpdateUserAccount(ctx context.Context, req *entities0.UpdateSFUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAccount", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAccount indicates an expected call of UpdateUserAccount.
func (mr *MockClientMockRecorder) UpdateUserAccount(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAccount", reflect.TypeOf((*MockClient)(nil).UpdateUserAccount), ctx, req)
}

// UpdateUserAddress mocks base method.
func (m *MockClient) UpdateUserAddress(ctx context.Context, req *entities0.UpdateSFAddressRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAddress", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAddress indicates an expected call of UpdateUserAddress.
func (mr *MockClientMockRecorder) UpdateUserAddress(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAddress", reflect.TypeOf((*MockClient)(nil).UpdateUserAddress), ctx, req)
}
