// Code generated by MockGen. DO NOT EDIT.
// Source: shared/vendors/shipping/shipengine/service/service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/nurdsoft/nurd-commerce-core/shared/vendors/shipping/shipengine/entities"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetRatesEstimate mocks base method.
func (m *MockService) GetRatesEstimate(ctx context.Context, from, to entities.ShippingAddress, dimensions entities.Dimensions) ([]entities.EstimateRatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatesEstimate", ctx, from, to, dimensions)
	ret0, _ := ret[0].([]entities.EstimateRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatesEstimate indicates an expected call of GetRatesEstimate.
func (mr *MockServiceMockRecorder) GetRatesEstimate(ctx, from, to, dimensions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatesEstimate", reflect.TypeOf((*MockService)(nil).GetRatesEstimate), ctx, from, to, dimensions)
}
