name: Deploy image to Cloud Run via WIF
on:
  push:
    branches:
      - main
      - 'release/*' 
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed to publish to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store GCP project ID as a secret in GitHub
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Use the service account key stored in GitHub secrets
          export_default_credentials: true
      
      # - name: Authenticate to GCP using WIF
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      
      - name: Test GCP access
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
          gcloud auth list
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image=ghcr.io/nurdsoft/nurd-commerce:latest \
            --region=${{ secrets.GCP_REGION }}\
            --platform=managed
