name: Deploy image to Cloud Run via WIF
on:
  push:
    branches:
      - main
      - 'release/*' 
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed to publish to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          release-type: node
          default-branch: main
      
      - name: Authenticate to GCP using WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      
      - name: Test GCP access
        run: |
          gcloud auth list
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image=ghcr.io/nurdsoft/nurd-commerce:latest \
            --region=${{ secrets.GCP_REGION }}\
            --platform=managed
