name: Run Tests

on:
  pull_request:
    branches:
      - '**'  # Run on PRs to all branches
  workflow_dispatch:  # Allow manual triggering

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git
        run: |
          apt update
          apt install -y git
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Run tests
        run: go test -v ./...
        
      - name: Run build
        run: go build -o go_build_nurd-commerce . 