// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wishlist/wishlistclient/client.go

// Package wishlistclient is a generated GoMock package.
package wishlistclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/nurdsoft/nurd-commerce-core/internal/wishlist/entities"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BulkRemoveFromWishlist mocks base method.
func (m *MockClient) BulkRemoveFromWishlist(ctx context.Context, req *entities.BulkRemoveFromWishlistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRemoveFromWishlist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkRemoveFromWishlist indicates an expected call of BulkRemoveFromWishlist.
func (mr *MockClientMockRecorder) BulkRemoveFromWishlist(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRemoveFromWishlist", reflect.TypeOf((*MockClient)(nil).BulkRemoveFromWishlist), ctx, req)
}
